apiVersion: v1
kind: Service
metadata:
  name: {{ include "pencraft.frontendName" . }}
spec:
  selector:
    app: {{ include "pencraft.frontendName" . }}
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
