backend:
  image: "asia-south1-docker.pkg.dev/PROJECT-ID/pencraft/java-store:prod"
  replicaCount: 3

frontend:
  image: "asia-south1-docker.pkg.dev/PROJECT-ID/pencraft/frontend:prod"
  replicaCount: 3
